#!/bin/sh
#
# Alsa config
#

source /etc/profile

start() {
    printf "Restore alsa"
    alsactl restore
    echo "OK"
}

stop() {
    printf "Store alsa"
#   alsactl store
    echo "OK"
}

restart() {
    stop
    start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
